/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JPanel;
import javax.swing.JToolBar;

/**
 *
 * @author Boxvi
 */
public class VPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VPrincipal
     */
    public VPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        tlbManPersonas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Principal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPrin = new javax.swing.JMenu();
        mantePersonas = new javax.swing.JMenu();
        reporPersonas = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 0, 102));
        jPanel2.setForeground(new java.awt.Color(153, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);

        tlbManPersonas.setToolTipText("Mantenimiento de Personas");
        tlbManPersonas.setFocusable(false);
        tlbManPersonas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tlbManPersonas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(tlbManPersonas);

        jPanel2.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 40));

        jLabel1.setText("VERSION 1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 700, 30));

        javax.swing.GroupLayout PrincipalLayout = new javax.swing.GroupLayout(Principal);
        Principal.setLayout(PrincipalLayout);
        PrincipalLayout.setHorizontalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1160, Short.MAX_VALUE)
        );
        PrincipalLayout.setVerticalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jPanel2.add(Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1160, 460));

        menuPrin.setText("PERSONA");

        mantePersonas.setText("MANTENIMIENTO PERSONAS");
        menuPrin.add(mantePersonas);

        reporPersonas.setText("REPORTE DE PERSONA");
        menuPrin.add(reporPersonas);

        jMenu4.setText("SALIR");
        menuPrin.add(jMenu4);

        jMenuBar1.add(menuPrin);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Principal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu mantePersonas;
    private javax.swing.JMenu menuPrin;
    private javax.swing.JMenu reporPersonas;
    private javax.swing.JButton tlbManPersonas;
    // End of variables declaration//GEN-END:variables

    public JDesktopPane getPrincipal() {
        return Principal;
    }

    public void setPrincipal(JDesktopPane Principal) {
        this.Principal = Principal;
    }

    public JMenu getMantePersonas() {
        return mantePersonas;
    }

    public void setMantePersonas(JMenu mantePersonas) {
        this.mantePersonas = mantePersonas;
    }

    public JMenu getMenuPrin() {
        return menuPrin;
    }

    public void setMenuPrin(JMenu menuPrin) {
        this.menuPrin = menuPrin;
    }

    public JMenu getReporPersonas() {
        return reporPersonas;
    }

    public void setReporPersonas(JMenu reporPersonas) {
        this.reporPersonas = reporPersonas;
    }

    public JButton getTlbManPersonas() {
        return tlbManPersonas;
    }

    public void setTlbManPersonas(JButton tlbManPersonas) {
        this.tlbManPersonas = tlbManPersonas;
    }

   
    
}
